# Generated by Django 5.2.1 on 2025-05-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_filtered',
            field=models.BooleanField(default=False, verbose_name='contenu filtré'),
        ),
        migrations.AddField(
            model_name='message',
            name='masked_items',
            field=models.JSONField(blank=True, default=list, verbose_name='éléments masqués'),
        ),
        migrations.AddField(
            model_name='message',
            name='original_content',
            field=models.TextField(blank=True, verbose_name='contenu original'),
        ),
    ]
