# Generated by Django 5.2.1 on 2025-05-14 16:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_message_is_filtered_message_masked_items_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_content', models.TextField(verbose_name='contenu original')),
                ('blocking_reason', models.JSONField(default=list, verbose_name='raisons du blocage')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_attempts', to='communications.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tentative de message bloqué',
                'verbose_name_plural': 'tentatives de messages bloqués',
                'db_table': 'findam_message_attempts',
                'ordering': ['-created_at'],
            },
        ),
    ]
