# Generated by Django 4.2.7 on 2025-05-05 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('credit_card', 'Carte de crédit'), ('bank_account', 'Compte bancaire')], max_length=20, verbose_name='type de paiement')),
                ('is_default', models.BooleanField(default=False, verbose_name='méthode par défaut')),
                ('is_verified', models.BooleanField(default=False, verbose_name='vérifiée')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='nom de la méthode')),
                ('account_number', models.CharField(blank=True, max_length=30, verbose_name='numéro de compte/carte')),
                ('account_name', models.CharField(blank=True, max_length=100, verbose_name='titulaire du compte')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='numéro de téléphone')),
                ('operator', models.CharField(blank=True, max_length=20, verbose_name='opérateur')),
                ('last_digits', models.CharField(blank=True, max_length=4, verbose_name='derniers chiffres')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name="date d'expiration")),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='nom de la banque')),
                ('branch_code', models.CharField(blank=True, max_length=20, verbose_name="code d'agence")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'méthode de paiement',
                'verbose_name_plural': 'méthodes de paiement',
                'db_table': 'findam_payment_methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('payment', 'Paiement de réservation'), ('refund', 'Remboursement'), ('payout', 'Versement au propriétaire'), ('subscription', 'Abonnement propriétaire'), ('commission', 'Commission plateforme'), ('adjustment', 'Ajustement manuel')], max_length=20, verbose_name='type de transaction')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('completed', 'Terminée'), ('failed', 'Échouée'), ('refunded', 'Remboursée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='statut')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant')),
                ('currency', models.CharField(default='XAF', max_length=3, verbose_name='devise')),
                ('external_reference', models.CharField(blank=True, max_length=100, verbose_name='référence externe')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('admin_notes', models.TextField(blank=True, verbose_name='notes administrateur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='date de traitement')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='bookings.booking')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='bookings.paymenttransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'db_table': 'findam_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant')),
                ('currency', models.CharField(default='XAF', max_length=3, verbose_name='devise')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='statut')),
                ('external_reference', models.CharField(blank=True, max_length=100, verbose_name='référence externe')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='début de la période')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='fin de la période')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('admin_notes', models.TextField(blank=True, verbose_name='notes administrateur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='date de traitement')),
                ('bookings', models.ManyToManyField(related_name='payouts', to='bookings.booking')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='payments.paymentmethod')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout', to='payments.transaction')),
            ],
            options={
                'verbose_name': 'versement',
                'verbose_name_plural': 'versements',
                'db_table': 'findam_payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='montant propriétaire')),
                ('tenant_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='montant locataire')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='montant total')),
                ('owner_rate', models.DecimalField(decimal_places=2, default=3.0, max_digits=5, verbose_name='taux propriétaire (%)')),
                ('tenant_rate', models.DecimalField(decimal_places=2, default=7.0, max_digits=5, verbose_name='taux locataire (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='bookings.booking')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission', to='payments.transaction')),
            ],
            options={
                'verbose_name': 'commission',
                'verbose_name_plural': 'commissions',
                'db_table': 'findam_commissions',
            },
        ),
    ]
