# Generated by Django 4.2.7 on 2025-05-10 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='escrow_reason',
            field=models.CharField(blank=True, max_length=100, verbose_name='raison de séquestre'),
        ),
        migrations.AddField(
            model_name='payout',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payout',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date programmée'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('scheduled', 'Programmé'), ('ready', 'Prêt à verser'), ('processing', 'En cours de traitement'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='statut'),
        ),
    ]
