# Generated by Django 5.2.1 on 2025-05-12 09:10

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payout_escrow_reason_payout_processed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'méthode de paiement', 'verbose_name_plural': 'méthodes de paiement'},
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Méthode activée pour les transactions'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='last_verification_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='notchpay_recipient_id',
            field=models.CharField(blank=True, help_text='ID du destinataire dans NotchPay', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de vérification'), ('verified', 'Vérifiée'), ('failed', 'Échec de vérification'), ('disabled', 'Désactivée')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='verification_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='branch_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='last_digits',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='nickname',
            field=models.CharField(blank=True, help_text='Nom personnalisé pour identifier cette méthode', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='operator',
            field=models.CharField(blank=True, choices=[('orange', 'Orange Money'), ('mtn', 'MTN Mobile Money')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank_account', 'Compte bancaire'), ('credit_card', 'Carte bancaire')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide. Format attendu: 6XXXXXXXX ou +237 6XXXXXXXX', regex='^(\\+237)?[6][5-9]\\d{7}$')]),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_type', 'mobile_money'), ('status__in', ['verified', 'pending'])), fields=('user', 'payment_type', 'phone_number'), name='unique_mobile_money_per_user'),
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_active_payment_method_per_user'),
        ),
    ]
