# Generated by Django 5.2.1 on 2025-05-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentmethodchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Méthode activée pour les transactions'),
        ),
    ]
