# Generated by Django 4.2.7 on 2025-05-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Clé de configuration', max_length=100, unique=True)),
                ('value', models.CharField(help_text='Valeur de configuration', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description de cette configuration')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration système',
                'verbose_name_plural': 'Configurations système',
            },
        ),
    ]
