# Generated by Django 5.2.1 on 2025-05-15 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_latitude_alter_property_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cities/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='city',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='ville en vedette'),
        ),
        migrations.AddField(
            model_name='city',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date de mise à jour'),
        ),
    ]
