# Generated by Django 5.2.1 on 2025-05-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_promocode_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='external_client_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='nom du client externe'),
        ),
        migrations.AddField(
            model_name='booking',
            name='external_client_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='téléphone du client externe'),
        ),
        migrations.AddField(
            model_name='booking',
            name='external_notes',
            field=models.TextField(blank=True, verbose_name='notes sur la réservation externe'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_external',
            field=models.BooleanField(default=False, verbose_name='réservation externe'),
        ),
    ]
